[mgr]
show_hidden = true

[[opener.edit]]
run = 'nvim %s'
block = true
for = "unix"

[[opener.open]]
run = 'xdg-open %s'
orphan = true
desc = "Open"

[[opener.set-wallpaper]]
run = '$HOME/.config/hypr/sethp.sh %s1'
for = "linux"
desc = "Set Wallpaper"

[[open.prepend_rules]]
url = "*.{jpg,jpeg,png}"
use  = [ "set-wallpaper", "open" ]
